server:
  port: 2020

feign:
  hystrix:
    enabled: true

spring:
  datasource:
    url: jdbc:h2:mem:Libro
    driver-class-name: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2
      settings:
        web-allow-others: true
        trace: false
  application:
    name: libro

eureka:
  client:
    fetch-registry: true
    serviceUrl:
      defaultZone: http://${registry.host:localhost}:${registry.port:8761}/eureka/
